// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4nKH2P3ZdjXqmPRrcNTrOPQlmTpaJ-CU',
    appId: '1:1065736291499:web:18ee3ce7735167cee123ee',
    messagingSenderId: '1065736291499',
    projectId: 'psiuteste-feea4',
    authDomain: 'psiuteste-feea4.firebaseapp.com',
    storageBucket: 'psiuteste-feea4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEG0IqyBONXBS5oBe2xjJh8HmQYmU83P0',
    appId: '1:1065736291499:android:477ac99c43a49290e123ee',
    messagingSenderId: '1065736291499',
    projectId: 'psiuteste-feea4',
    storageBucket: 'psiuteste-feea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUbZDw_fmW7vsjH_jVc8pnBQgO4TuSPoM',
    appId: '1:1065736291499:ios:392d6fa0e4c89b2ce123ee',
    messagingSenderId: '1065736291499',
    projectId: 'psiuteste-feea4',
    storageBucket: 'psiuteste-feea4.appspot.com',
    iosClientId: '1065736291499-1t8o828p6dlfhl90gj3509f681pb0hsm.apps.googleusercontent.com',
    iosBundleId: 'br.com.apptech.psiuteste',
  );
}
